### ISSUE TITLE
About Vue

### ISSUE THREAD

**Issue by donrsh** [nobodxbodon/one-China#2]
Hey, it seems Vue also violates the ONE-CHINA policy. See this [event](https://github.com/vuejs/events/issues/36).

Please list it. Thanks.

**Comment by nobodxbodon** [comment]
I don't see how, as the author [stated](https://github.com/vuejs/events/issues/36#issuecomment-497290540) clearly:

> The list contains both countries AND regions.

More importantly, this repo is specific for the open-source projects that have **contents** containing inconsistency, no matter the personal view of the project owner. Looking forward to reports about them.

Thanks.
